### ISSUE TITLE
ArchLinux clang-svn failure

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#18]
The build of the clang-svn container (based on ArchLinux) fails on:
```
error: In-source builds are not allowed. Please configure from a separate build directory!
```
See for example [that build failure on the Docker Hub](https://registry.hub.docker.com/u/cgal/testsuite-docker/build_id/67256/code/bk4vie5jcssfk4b6pebu96/).

Is not there a special package from ArchLinux that already packages a clang version for far from being the up-to-date svn version?

**Comment by bo0ts** [comment]
The build is already using the `llvm-svn` package. Unfortunately this package has not yet been adapted and it will likely not happen before the transition from aur to aur4 is complete. Until then this package will unfortunately fail to build. As soon as the issue is fixed upstream the package will magically build again.

**Comment by lrineau** [comment]
I suggest we remove the automatic build of that image. The mail sent by Docker Hub is really annoying. If we read those mails carefully, then that one is annoying, and otherwise if we do not read those mails, then we can miss another build failure.

**Comment by lrineau** [comment]
I have removed `Archlinux-clang-svn` from the automatic builds, in two steps:
  - first swap the first two lines, by editing the text,
  - then remove the second line (as you pointed out, there is no button to remove the first line).

**Comment by bo0ts** [comment]
UI hackery at its best. Well done.
