### ISSUE TITLE
A random network error "Remote end closed connection"

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#19]
[That Debian build][1] failed with:
> Failed to fetch http://httpredir.debian.org/debian/pool/main/g/glew/libglew1.10_1.10.0-3_amd64.deb  Error reading from server. Remote end closed connection [IP: 5.153.231.35 80]

Is there something we can do to protect our builds from those errors?

[1]: https://registry.hub.docker.com/u/cgal/testsuite-docker/build_id/67256/code/blc5blu7bkzpj9pmmngnocz/

**Comment by bo0ts** [comment]
I'm wondering about that since those errors happened the first time and I cannot reproduce them locally.

http://serverfault.com/questions/690639/api-get-error-reading-from-server-under-docker suggests to `apt-get clean` before an update. I don't see why that should be necessary (should `update` not check if the cache has been invalidated?!), but maybe it will help.

**Comment by lrineau** [comment]
Could it be that the base image contains a cache that apt uses?

Then the `apt-get clean` cleans up the caches and re-initialize them.

**Comment by bo0ts** [comment]
17af85a adds `apt-get clean`. Let's reopen this if the problem keeps coming up.

**Comment by lrineau** [comment]
There was [another build failure, today](https://registry.hub.docker.com/u/cgal/testsuite-docker/build_id/67256/code/bz3psysrdnspup6u7h4l3vj/), but `apt-get clean && apt-get update` was called.

I wonder why `apt` does not try with another mirror, in case of a failure.
