### ISSUE TITLE
Fancy names for containers

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#2]
I would like containers to have names, instead of the random-generated one.

I suggest name like: CGAL-*version*-*image* (eg: `CGAL-4.7-I-16-ArchLinux`). Let's discuss about other names: maybe without the CGAL version, as there should not be two versions tested at the same time.

**Comment by lrineau** [comment]
Probably there should be `-testsuite-` in the name.

**Comment by bo0ts** [comment]
Dropping the version would be nice, since it is very hard to extract reliably: when `--use-local` is enabled we don't have LATEST and we would need to extract the version from `version.h`, which is generated by cmake.

I'll implement something like `CGAL-${CGAL_TEST_PLATFORM}-testsuite` as the name.
