### ISSUE TITLE
Build failure for ArchLinux-clang

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#31]
The ArchLinux-clang Dockerfile does not build.

https://hub.docker.com/r/cgal/testsuite-docker/builds/bfhjkzjgunqsb973fuyyz3g/

In the step
```
RUN pacman -S --noconfirm clang && pacman -Scc --noconfirm
```
the error is:
> failed retrieving file 'clang-3.6.2-2-x86_64.pkg.tar.xz'

**Comment by bo0ts** [comment]
Bug of outdated images. This build tries to use the old ArchLinux image which has outdated packaging information. If the build is rerun, it will succeed.

We cannot update the packaging information in each individual build, because then we might have to update some packages, which would lead to inconsistencies between the base image and the current image.

**Comment by lrineau** [comment]
Use `ONBUILD`?

**Comment by lrineau** [comment]
I confirm the build is still broken:
https://hub.docker.com/r/cgal/testsuite-docker/builds/bmxlawfqthvsxbnakbxfyhg/

The date of the build failure report is: `Tue, 29 Sep 2015 18:07:53 -0000`.
