### ISSUE TITLE
Our ArchLinux image no longer build

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#50]
https://hub.docker.com/r/cgal/testsuite-docker/builds/bxanrrqwqheuk8ah3shgmha/

@akobel Would you have time to have a look at that build issue?

**Comment by akobel** [comment]
Hi @lrineau, just came back to the office from my vacation. I will have a look as soon as possible; shouldn't be a big issue.

On a related note, can you point me to a short description and/or give me the necessary commands how to perform an actual run of (parts of) the testsuite in a Docker image after the build?

**Comment by lrineau** [comment]
In principle all the document you need is supposed to be in the [README.md] written by Philipp. Let me know if you have questions, so that we can improve the documentation.

Maybe just do not forget to use the `-t <name>` option to `docker build` so that you can refer to an image by a named, instead of the hash ID.

[README.md]: https://github.com/CGAL/cgal-testsuite-dockerfiles/blob/master/README.md

**Comment by akobel** [comment]
Okay, got it. The issue was indeed that my version of docker-py (as shipped with Debian) was too old, and for some obscure reason, I cannot build on my native Arch installation because /etc/resolv.conf is missing during the build, so I have no network connection within the virtual environment to get the required packages. Any hint on that is appreciated.

You might want to add on the [https://github.com/CGAL/cgal-testsuite-dockerfiles/blob/master/README.md](README.md) that
- the proper way to install docker-py on such distros is `pip install docker-py`
- `--username` should be `--user` for `test_cgal.py`, and means the credentials used for the HTTP auth on the wiki page

I will try to have a look at the Ak_d testsuite within the Arch image when time allows, and see what I can do to test the LEDA- and GMP-based kernels as well as RS. OTOH, I might defer this until you finished the cleanup of the CMake build process and removed the preconfiguration phase for 3rd-party libs. Or is this already done?


HTH,
Alexander

**Comment by lrineau** [comment]
I have fixed the README in 08607e673f45076e989f2500d724cee101e3f8d0.

As for the CMake changes, they are not yet pushed to `master`. Our testsuite infrastructure just got ready for it (install CMake>=3.1 on all test machines).

**Comment by akobel** [comment]
Looks good, thanks. I guess everything else was trouble with my individual docker setup (not the proper access rights for my user etc.).

I'll wait for the CMake changes in `master` then before following up with a more detailed look at the actual testsuite runs on those images (including an investigation for CGAL/cgal#1374).
